# Generated by Django 4.0.6 on 2023-01-12 12:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='name of the discount applied to products if any')),
                ('dis_desc', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description of discount')),
                ('dis_per', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dis_active', models.BooleanField(default=True, verbose_name='current status of the discount')),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_tot', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total value of the order')),
            ],
        ),
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_cat_name', models.CharField(max_length=60, unique=True, verbose_name='product category name')),
                ('p_cat_desc', models.TextField(max_length=1000, verbose_name='product category description in detail')),
            ],
        ),
        migrations.CreateModel(
            name='Product_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_inv_qty', models.PositiveIntegerField(verbose_name='inverntory quantity of the product')),
                ('p_last_add_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='last added quantity of product in units')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.PositiveIntegerField()),
                ('created_at', models.TimeField(default=datetime.datetime(2023, 1, 12, 17, 51, 54, 389914))),
                ('modified_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Saved_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=60)),
                ('address_line_2', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.PositiveIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=120, verbose_name='product name')),
                ('p_desc', models.CharField(max_length=1000, verbose_name='product detailed description')),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='mrp of the product')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.product_category')),
                ('discount_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.discount')),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.product_inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_amt', models.PositiveIntegerField(verbose_name='the amount paid by the customer')),
                ('transaction_id', models.PositiveIntegerField(verbose_name='id receieved from payment gateway')),
                ('pay_sta', models.CharField(choices=[('S', 'Successful'), ('P', 'Pending'), ('F', 'Failed')], max_length=1, verbose_name='Payment status  as S/P/F')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order_details')),
            ],
        ),
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity of the product in this order')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order_details')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.products')),
            ],
        ),
        migrations.AddField(
            model_name='order_details',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.payment_details'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_cart_qty', models.PositiveIntegerField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.products')),
            ],
        ),
    ]
