# Generated by Django 4.0.6 on 2023-01-12 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_details',
            new_name='Order_detail',
        ),
        migrations.RenameModel(
            old_name='Order_items',
            new_name='Order_item',
        ),
        migrations.RenameModel(
            old_name='Payment_details',
            new_name='Payment_detail',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 1, 12, 18, 28, 31, 566867)),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_at',
            field=models.TimeField(blank=True),
        ),
    ]
